name: SAST PR Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_URL: https://snowflake.semgrep.dev
      PUBLISH_DEPLOYMENT: 1
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep:latest
    if: (github.actor != 'dependabot[bot]' && !contains(github.event.pull_request.title, 'PR Canary'))
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
