---
name: Reusable workflow for dispatch

on:
  workflow_call:
   secrets:
     token:
       required: true

permissions:
  contents: read

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_URL: https://snowflake.semgrep.dev
      SEMGREP_TIMEOUT: 90
      PUBLISH_DEPLOYMENT: 1
      SEMGREP_APP_TOKEN: ${{ secrets.token }}
    container:
      image: returntocorp/semgrep:latest
    if: (github.actor != 'dependabot[bot]' && !contains(github.event.pull_request.title, 'PR Canary'))
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --verbose --dry-run
